language: python

python:
    - "3.6"
env:
   - export APP_SETTINGS=testings
   - export DATABASE_URL2=postgresql://postgres:password@localhost/test_db

# install dependency
services:
  - postgresql

before_script:
- psql -c 'create database food_db;' -U postgres

install: 
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov


script:
  - coverage run --source=. -m unittest discover
  - coverage report

after_success: 
- coveralls
