language: python

python:
    - "3.6"

# install dependency
services:
  - postgresql

before_script:
- psql -c 'create database food_db;' -U postgres
- psql -c 'create database test_db;' -U postgres

install: 
  - pip install -r requirements.txt
  - pip install python-nose

script:
  - nosetests -v --with-coverage --cover-package="app"
  - coverage report

after_success: 
- coveralls
