language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov


script:
  - coverage run --source=. -m unittest discover
  - coverage report


after_success: 
- coveralls