language: python

python:
    - "3.6"

# install dependency
services:
  - postgresql

before_script:
- psql -c 'create database food_db;' -U postgres

install: 
  - pip install -r requirements.txt
  - python install pytest-cov

script:
  - coverage run --source=. -m unittest discover
  - coverage report

after_success: 
- coveralls
